### PR TITLE
Add timeout and remove HTTP verbs

### PR DESCRIPTION
**Pull request by fabaff**
- Add timeout for requests
- Remove unsupported [HTTP verbs](https://docs.opnsense.org/development/api.html#introduction)

### CODE REVIEW

**Comment by mtreinish** [comment]
Hmm, I'm not sure why coveralls is set to block merge on changes. I never intended to use it for that (although I don't even remember setting it up on this project) I only wanted it to aggregate coverage so it could be tracked. Not enforce all changes increase coverage. Let me see if I can turn that off.

**Comment by mtreinish** [comment]
ok, the coveralls side shouldn't block anymore. Can you respin this to fix the conflict? I'm still not sure about the test removal, but I guess they don't really add that much value.

**Comment by fabaff** [comment]
You can't test something that is no longer there.

Now, I will start with the Home Assistant integration as you already did the heavy lifting.

**Comment by mtreinish** [comment]
Heh, I don't know what I was thinking. I completely missed you were removing the unused HTTP verb methods and for some reason thought it was just dropping tests.

Anyway this LGTM now. Thanks!

**Comment by mtreinish** [comment]
Do you need/want me to push a new release with your fixes now so you can leverage that in Home Assistant?

**Comment by fabaff** [comment]
Let's wait a little bit with the release perhaps there are other things we could address before releasing an update.

**Pull request merged**
